# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Real Big Playbook
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/playbook" # the subpath of your site, e.g. /blog
url: "http://realbig.github.io/playbook" # the base hostname & protocol for your site
twitter_user: gorealbig
github_user: realbig
permalink: /:categories/:title
collections:
    posts:
        output: true
        permalink: /:year/:month/:day/:title/
    pages:
        output: true
        permalink: /:path/
    process: 
        output: true
        permalink: /process/:path/
    contributing: 
        output: true
        permalink: /contributing/:path/

# Build settings
markdown: kramdown
highlighter: rouge

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tag/:name/
    category: /category/:name/
    
data:
    nav-main:
        -
            url: /about/
            text: 'About'
        -
            url: /contributing/
            text: 'Contributing'
    
gems:
  - jekyll-archives
  - jekyll-sitemap

exclude:
  - "/assets/"
  - "/build/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "production.sh"
  - "init.sh"